###############################################

# Run GitHub's Super Linter against code base #

###############################################



name: GitHub's Super Linter
on: push

jobs:
 run-linters:
  name: GitHub's Super Linter
  runs-on: ubuntu-latest

  steps:
   - name: ICS4U-Unit1-05-Java
     uses: actions/checkout@master
   - name: Run GitHub Super Linter
     uses: github/super-linter@master
  env:
   VALIDATE_ALL_CODEBASE: true
   DEFAULT_BRANCH: main
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
